
databricks_dev:
  target: dev
  outputs:
    dev:
      host: "adb-1318386233821596.16.azuredatabricks.net"
      http_path: "sql/protocolv1/o/1318386233821596/0716-092643-5iin5cl6"
      catalog: hive_metastore
      schema: grp_dataeng_dbtdev
      threads: 2
      type: databricks
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"

databricks_staging:
  target: stg
  outputs:
    stg:
      host: "adb-2482814744621547.7.azuredatabricks.net"
      http_path: "sql/protocolv1/o/2482814744621547/0716-155236-mvtlpqex"
      catalog: hive_metastore
      schema: grp_dataeng_dbtstg
      threads: 2
      type: databricks
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"

