bundle:
  name: energy_model
  
experimental:
  python_wheel_wrapper: true

include:
  - workflows/*.yml

targets:
  dev:
    mode: development
    default: true
    workspace:
      host: DATABRICKS_HOST
    run_as:
      service_principal_name: azure_client_id

  staging:
    mode: production
    run_as: 
      service_principal_name: azure_client_id

variables:
  profiles_dir:
    description: The directory where the DBT profiles are stored
    default: ./.github/dbt_profiles

  catalog:
    description: The default catalog to use for DBT
    default: grp_dataeng_dbtdev

  dbt_runner:
    description: The runner to use for DBT
    lookup:
      cluster: grp-dataeng-dev

  max_concurrent_runs:
    description: The common max_concurrent_runs for all jobs
    default: 1

permissions:
  description: The common permissions for all jobs
  type: complex
  default:
    - group_name: ags-dap-u-deg-dev
      level: CAN_MANAGE
    - group_name: ags-dap-u-deg-stg
      level: CAN_MANAGE
    - user_name: ram.krishna@centrica.com
      level: CAN_MANAGE_RUN
