bundle:
  name: energy_model
  
experimental:
  python_wheel_wrapper: true

include:
  - workflows/*.yml

targets:
  dev:
    mode: development
    default: true
    workspace:
    host:  ${{ secrets.HOST }}
    run_as: 10971450-b399-4a24-bcbb-6c3d7300c858
    
  staging:
    mode: production
    default: true
    workspace:
    host:  ${{ secrets.HOST }}
    run_as: 69707254f-e89d-4c6b-81d9-d2b72a458827

variables:
  profiles_dir:
    description: The directory where the DBT profiles are stored
    default: ./.github/dbt_profiles

  catalog:
    description: The default catalog to use for DBT
    default: grp_dataeng_dbtdev

  dbt_runner:
    description: The runner to use for DBT
    lookup:
      cluster: grp-dataeng-dev

  max_concurrent_runs:
    description: The common max_concurrent_runs for all jobs
    default: 1

  git_source:
    description: The common git_source for all jobs
    type: complex
    default:
      git_url: ${bundle.git.origin_url}
      git_provider: gitHub
      git_branch: main

  permissions:
    description: The common permissions for all jobs
    type: complex
    default:
      - group_name: ags-dap-u-deg-dev
        level: CAN_MANAGE
