name: Deploy pipeline - develop

on:
  workflow_dispatch:

env:
  DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
  DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
  DATABRICKS_HOST: adb-246130164057717.17.azuredatabricks.net
  DATABRICKS_AUTH_TYPE: oauth-m2m

jobs:
  deploy:
    name: "Deploy pipeline"
    environment: develop
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Check and echo .databrickscfg
        run: |
          if [ -f ~/.databrickscfg ]; then
            cat ~/.databrickscfg
          else
            echo ".databrickscfg file not found in home directory"
          fi
      - name: Print Databricks environment variables
        run: |
          echo "DATABRICKS_HOST: $DATABRICKS_HOST"
          echo "DATABRICKS_AUTH_TYPE: $DATABRICKS_AUTH_TYPE"
