name: Develop pipeline

on:
  workflow_dispatch:

env:
    host: ${{ secrets.HOST }}
    azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
    azure_client_id: ${{ secrets.DATABRICKS_CLIENT_ID }}
    azure_client_secret: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
    DATABRICKS_BUNDLE_ENV: dev
    
jobs:
  deploy:
    name: "Deploy pipeline"
    environment: develop
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: debug deployment
        run: databricks current-user me --debug
      - name: Deploy DBT pipeline
        run: databricks bundle deploy

