name: Deploy pipeline - develop

on:
  workflow_dispatch:

env:
    DATABRICKS_HOST: "adb-2482814744621547.7.azuredatabricks.net"
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    ARM_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
    
jobs:
  deploy:
    name: "Deploy pipeline"
    environment: develop
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: debug deployment
        run: databricks current-user me --debug
      - name: Deploy DBT pipeline
        run: databricks bundle validate
