name: Develop pipeline

on:
  workflow_dispatch:

env:
    DATABRICKS_HOST: ${{ secrets.HOST }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    ARM_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
    
jobs:
  deploy:
    name: "Deploy pipeline"
    environment: develop
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: debug deployment
        run: databricks current-user me --debug --target dev
      - name: Deploy DBT pipeline
        run: databricks bundle deploy --target dev
