name: Deploy pipeline - develop

on:
  workflow_dispatch:

env:
  DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
  DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
  DATABRICKS_HOST: adb-246130164057717.17.azuredatabricks.net
  DATABRICKS_AUTH_TYPE: oauth-m2m
  DATABRICKS_WAREHOUSE_ID: "246130164057717/0321-105834-2j7zjzjd"
  DBT_PROFILES_DIR: .github/dbt_profiles


jobs:
  deploy:
    name: "Deploy pipeline"
    environment: develop
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Deploy DBT pipeline
        run: databricks bundle deploy