name: Deploy pipeline - develop

on:
  workflow_dispatch:

env:
  DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
  DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
  DATABRICKS_HOST: adb-246130164057717.17.azuredatabricks.net
  DATABRICKS_AUTH_TYPE: oauth-m2m

jobs:
  deploy:
    name: "Deploy pipeline"
    environment: develop
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Echo .databrickscfg file
        run: cat ~/.databrickscfg
      - name: Deploy DBT pipeline
        run: databricks bundle validate
