name: Deploy pipeline - develop

on:
  workflow_dispatch:

env:
  DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
  DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
  DATABRICKS_HOST: adb-1318386233821596.16.azuredatabricks.net
  DATABRICKS_AUTH_TYPE: oauth-m2m
  TOKEN_ENDPOINT_URL: https://adb-1318386233821596.16.azuredatabricks.net/oidc/v1/token

jobs:
  deploy:
    name: "Deploy pipeline"
    environment: develop
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Get OAuth 2.0 Token
        run: |
          response=$(curl --request POST \
          --url $TOKEN_ENDPOINT_URL \
          --user "$DATABRICKS_CLIENT_ID:$DATABRICKS_CLIENT_SECRET" \
          --data 'grant_type=client_credentials&scope=all-apis')
          echo "ACCESS_TOKEN=$(echo $response | jq -r .access_token)" >> $GITHUB_ENV
      - name: View GITHUB_ENV
        run: cat $GITHUB_ENV
      - name: debug deployment
        run: databricks current-user me --debug
      - name: Deploy DBT pipeline
        run: databricks bundle validate
