name: Develop pipeline

on:
  workflow_dispatch:
    
jobs:
  deploy:
    name: "Deploy pipeline"
    environment: develop
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deploy
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: debug deployment
        run: databricks current-user me --debug
      - name: Deploy DBT pipeline
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          DATABRICKS_BUNDLE_ENV: dev
          DATABRICKS_CLUSTER_ID: ${{ secrets.DATABRICKS_CLUSTER_ID }}
        run: databricks bundle deploy -t dev

