name: Deploy pipeline

on:
    workflow_dispatch:
      

env:
  DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
  DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
  DATABRICKS_HOST: adb-1318386233821596.16.azuredatabricks.net
  DATABRICKS_AUTH_TYPE: oauth-m2m
  DATABRICKS_WAREHOUSE_ID: "1318386233821596/0716-092643-5iin5cl6"
  DBT_PROFILES_DIR: .github/dbt_profiles
  DBT_STATE: ./state

jobs:
  deploy:
    name: "Deploy pipeline"
    environment: develop
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4.1.7
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0
      - name: setup dbt
        run: |
          python3 -m pip install poetry
          poetry install
          poetry run dbt deps
      - name: Inline shell script
        run: | 
            ls -ahl
            pwd
      - name: Compile DBT
        run: |
          poetry run dbt debug

