name: Mirror All Branches

on:
   workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Configure SSH for destination repository
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MIRROR_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Push all branches to destination repository
        run: |
          git remote add destination git@github.com:USERNAME/DEST_REPO.git
          # Push all branches to destination
          git push --mirror destination