name: Mirror Repository

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to mirror repository
        env:
          SOURCE_REPO: ${{ github.server_url }}/${{ github.repository }}.git
          MIRROR_REPO: https://${{ secrets.MIRROR_PAT }}@github.com/Ram-Dev7/test-mirror.git
        run: |
          git remote add mirror $MIRROR_REPO
          git push --mirror mirror