name: Mirror Repository

on:
    workflow_dispatch:
#   push:
#     branches:
#       - '*'
#   delete:
#     branches:
#       - '*'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Mirror to target repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:Ram-Dev7/test-mirror.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
